filebeat.inputs:
- type: filestream
  id: my-filestream-id
  enabled: false
  paths:
    - /var/log/*.log

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

output.elasticsearch:
  hosts: ["scheme://host:port"]
  username: "elastic"
  password: "password"
  index: elastic-logs-8
  ssl.certificate_authorities: ["/path-to-certs/elasticsearch-cert.crt"]
  ssl.keystore: ["/path-to-certs/http.p12"]
  
setup.template.name: "elastic-logs-8"
setup.template.pattern: "elastic-logs-8*"
setup.ilm.enabled: false

logging.level: info
